name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test on CI
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Running test
        run: |
          make test
